# GitHub Actions CI for luasteam
# Builds on Linux, macOS, and Windows

name: CI

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: buildpack-deps:20.04 # Older version is better for compatibility
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y build-essential g++-multilib
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Fix Git Trust
        # This tells git to ignore ownership checks for the current workspace
        run: git config --global --add safe.directory '*'
      - name: Download Steamworks SDK
        uses: actions/checkout@v6
        with:
          repository: rlabrecque/SteamworksSDK
          path: sdk
      - name: Build linux64
        run: make linux64 && mkdir -p build && cp luasteam.so build/linux64_luasteam.so
      - name: Build linux32
        run: make clean && make linux32 && cp luasteam.so build/linux32_luasteam.so
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: linux-binaries
          path: build/*.so

  build-linux-arm:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential 
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Download Steamworks SDK
        uses: actions/checkout@v6
        with:
          repository: rlabrecque/SteamworksSDK
          path: sdk
      - name: Build linux64
        run: |
          sset -e
          make linux64
          mkdir -p build
          cp luasteam.so build/linuxarm64_luasteam.so
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: linux-binaries-arm
          path: build/*.so

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Download Steamworks SDK
        uses: actions/checkout@v6
        with:
          repository: rlabrecque/SteamworksSDK
          path: sdk
      - name: Build
        run: make osx && mkdir -p build && cp luasteam.so build/osx_luasteam.so
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: macos-binaries
          path: build/*.so

  build-windows-luajit:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]
    steps:
      - name: Checkout LuaJIT
        uses: actions/checkout@v6
        with:
          repository: LuaJIT/LuaJIT
          path: luajit
      - name: Setup VS Dev Cmd
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: ${{ matrix.arch }}
      - name: Build
        shell: cmd
        working-directory: luajit/src
        run: msvcbuild.bat
      - name: Artifact
        uses: actions/upload-artifact@v6
        with:
          name: temp-luajit-${{ matrix.arch }}
          path: luajit/*
          if-no-files-found: error
          retention-days: 1

  build-windows:
    runs-on: windows-latest
    needs: build-windows-luajit
    strategy:
      matrix:
        arch: [x86, x64]
    defaults:
      run:
        shell: cmd
    steps:
      - name: Determine CMake Architecture
        id: arch
        run: |
          if "${{ matrix.arch }}" == "x86" (
            echo arch=Win32 >> %GITHUB_OUTPUT%
          ) else (
            echo arch=${{ matrix.arch }} >> %GITHUB_OUTPUT%
          )
      - uses: actions/checkout@v6
        with:
          submodules: false
      - name: Download Steamworks SDK
        uses: actions/checkout@v6
        with:
          repository: rlabrecque/SteamworksSDK
          path: sdk
      - name: Download LuaJIT Artifact
        uses: actions/download-artifact@v7
        with:
          name: temp-luajit-${{ matrix.arch }}
          path: luajit
      - name: Configure
        env:
          LUAJIT_DIR: ${{ github.workspace }}\luajit\src
        run: cmake -Bbuild -S. --install-prefix %CD%\installdir -A ${{ steps.arch.outputs.arch }}
      - name: Build
        run: cmake --build build --config RelWithDebInfo --target install
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: windows-binaries-${{ matrix.arch }}
          path: installdir/

  release:
    needs: [build-linux, build-linux-arm, build-macos, build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: build
      - name: List build outputs
        run: ls -R build
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/**/*.dll
            build/**/*.so
